name: random_images
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  aurora_random_image:
    path: ../aurora_random_image
  auto_route: ^10.2.0
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  injectable: ^2.6.0
  jsn_ui:
    path: ../packages/jsn_ui
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  network_sdk:
    path: ../packages/network_sdk
  palette_generator_master: ^1.0.1
  service_provider:
    path: ../packages/service_provider

# path: ^1.9.0
dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  lints: ^6.0.0
  test: ^1.25.6
