name: auth_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  network_sdk:
    path: ../network_sdk
  persistence_sdk:
    path: ../persistence_sdk

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
